### ISSUE TITLE
Mapper inside switch fails to compile

### ISSUE THREAD

**Issue by extremeheat** [extremeheat/protodef-yaml#10]
```yml
   has_cancel_reason: bool
   # CancelReason represents the reason why the form was cancelled.
   data: has_cancel_reason ?
      if true: u8 =>
         0: closed
         1: busy

``` 
fails, workaround works with anon field

```yml
   has_cancel_reason: bool
   # CancelReason represents the reason why the form was cancelled.
   _: has_cancel_reason ?
      if true:
         cancel_reason: u8 =>
            0: closed
            1: busy
```
