### ISSUE TITLE
Add check for switch with no fields

### ISSUE THREAD

**Issue by extremeheat** [extremeheat/protodef-yaml#11]
A check inside protodef-yaml for switch with no fields could catch [this error](https://github.com/PrismarineJS/minecraft-data/issues/750)

Also, maybe a new syntax for optionals would be nice, like this for optional struct:

```yaml
   HasQuiz: bool
   external_link_settings: ?
     has: bool
     url: string
     display_name: string
```

Or for a primitive, inlined:

```yaml
   HasQuiz: bool
   optional_field: ?bool
```
